config/routes.rb
Rails.application.routes.draw do
  #Errors
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]

  get 'users/index'

  #Devise
  devise_for :users, skip: [:sessions]
  as :user do
    post 'login', to: 'devise/sessions#create', as: :user_session
    match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session,
                   via: Devise.mappings[:user].sign_out_via
  end

  get 'home', to: 'home#index'
  get 'search', to: 'users#search'
  get '/users/showfollowing', to: 'users#showfollowing', as: 'showfollowing'
  get '/users/showfollowers', to: 'users#showfollowers', as: 'showfollowers'
  get '/users/follow/:id', to: 'followers#follow', as: 'follow'
  get '/users/unfollow/:id', to: 'followers#unfollow', as: 'unfollow'
  put 'like/:id', to: 'posts#like', as: 'like'

  resources :posts, except: [:show]
  resources :comments, except: [:show]
  resources :users, only: [:update, :show]
  resources :events, except: [:show]

  #Página inicial
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, :user, :post, presence: true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :current, :class_name => 'User', :foreign_key => 'current_id'
  belongs_to :follower, :class_name => 'User', :foreign_key => 'follower_id'

  #Scope
  scope :get_followers, -> (id) {Follower.where(follower_id: id)}

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  #Validations
  validates :content, :user, presence: true

  #Acts as votable - gem
  acts_as_votable

  #Relationships
  has_many :comments

  #Constants
  QT_PROFILE = 4

  #Scopes
  scope :by_user , -> (id, page) { where(user_id: id).order(updated_at: :desc).page(page).per(QT_PROFILE) }
  scope :subscribed, -> (following, page) { where(user_id: following).order(created_at: :desc).page(page).per(QT_PROFILE)}
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Relationships
  has_many :posts
  has_many :following, :class_name => 'Follower', :foreign_key => 'current_id'

  # User Avatar Validation
  validates :avatar, presence: true
  validates_integrity_of  :avatar
  validates_processing_of :avatar

  scope :filter_all, -> (page) {User.all}

  private

  def avatar_size_validation
    errors[:avatar] << "should be less than 500KB" if avatar.size > 0.5.megabytes
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :password_confirmation,
                                  :avatar, :avatar_cache,:about])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :password_confirmation,
             :current_password, :avatar, :avatar_cache, :remove_avatar,:about])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
  end

  def new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to root_path, notice: t("messages.created_with", item:"comment")
    else
      redirect_to root_path, alert: t("messages.error_with", item:"comment")
    end
  end

  def edit
    respond_to  do | format |
      format.js
      format.html { head :no_content }
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to root_path, notice: t("messages.update_with", item:"comment")
    else
      redirect_to root_path, alert: t("messages.update_error", item:"comment")
    end
  end

  def destroy
    if @comment.destroy
      redirect_to root_path, notice: t("messages.delete_with", item:"comment")
    else
      redirect_to root_path, alert: t("messages.delete_error", item:"comment")
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def error404
    render status: :not_found
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :authenticate_user!

  def follow
    @f = Follower.new
    @f.current = current_user
    @f.follower = User.find(params[:id])

    if @f.save!
        redirect_to root_path, notice: "Yay! You're following #{@f.follower.name}"
    else
        redirect_to root_path, error: "Error during following the profile #{@f.follower.name}"
    end

  end

  def unfollow
    @f = Follower.find(params[:id])
    if @f.destroy
        redirect_to root_path, notice: "Ok! Unfollow concluded successfully!"
    else
        redirect_to root_path, error: "Error during unfollow process"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def index
    @user = User.new

    unless current_user.blank?
      following_list = current_user.following
      @following =  following_list.order(:created_at).limit(6)

      values =  following_list.pluck(:follower_id)
      @posts = Post.subscribed(values, params[:page])
    end
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:edit, :update, :destroy, :like]

  def index
  end

  def new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to root_path, notice: t("messages.created_with", item:"post")
    else
      redirect_to root_path, alert: t("messages.error_with", item:"post")
    end
  end

  def edit
    respond_to  do | format |
      format.js
      format.html { head :no_content }
    end
  end

  def update
    if @post.update(post_params)
      redirect_to users_index_path, notice: t("messages.update_with", item:"post")
    else
      redirect_to users_index_path, alert: t("messages.update_error", item:"post")
    end
  end

  def destroy
    if @post.destroy
      redirect_to users_index_path, notice: t("messages.delete_with", item:"post")
    else
      redirect_to users_index_path, alert: t("messages.delete_error", item:"post")
    end
  end

  def like

    @post.like_by current_user
    redirect_back(fallback_location: root_path)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @posts = current_user.posts
    @following = current_user.following.order(:created_at).limit(6)
    @followers = Follower.get_followers(current_user.id).order(:created_at).limit(6)
  end

  def search
    cookies[:search_t] = params[:q]
        @users = User.filter_all(params[:page])

  end

  def show
     @user = User.friendly.find(params[:id])
  end

  def showfollowing
    @following = current_user.following
  end

  def showfollowers
    @followers = Follower.get_followers(current_user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :about, :avatar, :avatar_cache,
                                 :remove_avatar,:q)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/follower_helper.rb
module FollowerHelper
end

app/helpers/form_tag_helper.rb
module FormTagHelper
  # see http://api.rubyonrails.org/classes/ActionView/Helpers/FormTagHelper.html#method-i-utf8_enforcer_tag
  def utf8_enforcer_tag
    ''.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_modal.html.erb
<!-- Modal -->
<%= form_for @comment do |f| %>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Editing comment</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
              <%= f.label :content %>
              <%= f.text_area :content, class:"form-control", rows: 3 %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag "Update", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
<% end %>

app/views/comments/edit.js.erb
$("#edit-modal").html("<%= j render "modal" %>");
$("#edit-modal").modal('show');

app/views/home/index.html.erb
<% if user_signed_in? %>
  <section>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Wall</h3>
          </div>
          <div class="panel-body">
            <%= form_tag posts_path do%>
              <div class="form-group">
                <%= text_area :post, :content, class:"form-control", rows: 3, placeholder:"Write on the wall" %>
                <%= hidden_field :post, :user_id, value: current_user.id %>
              </div>
              <%= submit_tag "Submit", class: "btn btn-primary" %>

            <% end %>
          </div>
        </div>
            <br>
        <div class="panel panel-default post">
          <div class="panel-body">
             <% if @posts.blank? %>
              <div class="row">
                <p>You need to follow someone to see posts.</p>
              </div>
             <% else %>
               <% @posts.each do |p| %>
               <div class="row">
                 <div class="col-sm-2">
                    <%= link_to user_path(p.user), class: "post-avatar thumbnail" do %>
                      <%= image_tag(p.user.avatar.url(:thumb), alt: @user.name) %>
                    <% end %>
                    <div class="text-center"><%= p.user.name %></div>
                   <div class="likes text-center">
                     <%= pluralize(p.get_likes.size,"Like") %>
                   </div>
                 </div>
                 <div class="col-sm-10">
                   <div class="bubble">
                     <div class="pointer">
                       <p><%= p.content %></p>

                       <p class="properties">
                        <%= time_ago_in_words(p.updated_at) %>
                       </p>

                     </div>
                     <div class="pointer-border"></div>
                   </div>
                   <p class="post-actions">
                    <%= link_to "Like", like_path(p), method: :put %>
                   </p>
                   <br/>
                   <p style>Comments</p>

                   <% if p.comments.blank? %>
                      <%= render partial: "shared/comment", locals: {p: p} %>
                   <% end %>

                   <% p.comments.order(updated_at: :desc).each do |c| %>
                   <div class="comments">
                     <div class="comment">
                      <%= link_to '', class: "comment-avatar pull-left" do %>
                        <%= image_tag(c.user.avatar.url(:thumb)) %>
                      <% end %>

                       <div class="comment-text">
                        <!-- owner -->
                        <div class="pull-left properties">
                         <%= c.user.name %>
                        </div>

                         <!-- owner -->
                         <div class="pull-right properties">
                          <%= time_ago_in_words(c.updated_at) %>
                          <% if c.user == current_user %>
                              <%= link_to comment_path(c.id), method: :delete, data: {confirm: t('messages.confirm')} do %>
                                  <i class="fa fa-close"></i>
                               <% end %>

                              <%= link_to edit_comment_path(c.id), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal'} do %>
                                  <i class="fa fa-pencil"></i>
                               <% end %>

                          <% end %>
                         </div>

                         <div class="clearfix"></div>

                         <p><%= c.content %></p>
                       </div>

                     </div>
                     <div class="clearfix"></div>
                   </div>
                   <% end %>

                   <% unless p.comments.blank? %>
                      <%= render partial: "shared/comment", locals: {p: p} %>
                   <% end %>

                 </div>
               </div>
               <br/>
               <% end %>
              <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <%= render partial: "shared/following" %>
      </div>
    </div>
  </div>
  </section>
<% else %>
  <section>

  </section>
<% end %>
<div class=well>
<%unless user_signed_in?%>
<p>This is a social netwoking site<br>In this you can follow ur frds<br>you can post, like, comment </p>
<%end%>
</div>
<div id="edit-modal" class="modal fade" role="dialog"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialNetwork</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    <!-- header -->
    <%= render partial: "shared/header" %>
    <%= yield %>
    <%= render partial: 'shared/notifications' %>
  </body>
</html>

app/views/posts/_modal.html.erb
<!-- Modal -->
<br>
<%= form_for @post do |f| %>
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Editing post</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
              <%= f.label :content %>
              <%= f.text_area :content, class:"form-control", rows: 3 %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag "Update", class: "btn btn-primary" %>
          <br>
        </div>
      </div>
    </div>
<% end %>

app/views/posts/edit.js.erb
$("#edit-modal").html("<%= j render "modal" %>");
$("#edit-modal").modal('show');

app/views/shared/_comment.html.erb
<div class="comment-form">
 <%= form_tag comments_path, class: "form-inline" do%>
   <div class="form-group">
     <%= text_field :comment, :content, class:"form-control", placeholder:"Enter a comment" %>
     <%= hidden_field :comment, :post_id, value: p.id %>
     <%= hidden_field :comment, :user_id, value: current_user.id %>
   </div>
   <%= submit_tag "Add", class: "btn btn-default" %>
 <% end %>
</div>

app/views/shared/_following.html.erb
<div class="well"  background-color=lightblue>

<div class="panel panel-default friends">

  <div class="panel-body">
    <% unless @following.blank? %>
    <div class="panel-heading">
      <h3 class="panel-title">Following</h3>
    </div>
    <ul>
      <% @following.each do |fol| %>
        <li>
          <%= link_to user_path(fol.follower), class: "thumbnail" do %>
            <%= image_tag(fol.follower.avatar.url(:medium)) %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="clearfix"></div>
    <br>
    <%= link_to "View All", showfollowing_path, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/shared/_header.html.erb
<header>
<div class="container">
          <% if user_signed_in? %>
          <div class="pull-right">Welcome!, <%= current_user.name %></div><br>
    <div class="dropdown">
<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
  Options
</button>
       <div class="dropdown-menu">
<li class="dropdown">
        <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "My Profile", users_index_path %></li>
              <li><%= link_to "Following", showfollowing_path %></li>
              <li><%= link_to "Followers", showfollowers_path %></li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
            <% else %>
            </li></div>
              <%= link_to "Sign up", new_user_registration_path %>
              <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "form-inline"}) do |f| %>
                  <div class="form-group">
                    <%= f.label :email, class: "sr-only" %>
                    <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "Enter Email" %>
                  </div>

                  <div class="form-group">
                      <%= f.label :password, class: "sr-only" %>
                      <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password" %>
                    <%= f.submit "Sign in", class: "btn btn-default" %>
                    </div>
                  <br>
          <% end %>
            <% end %>
              </div>
              <% if user_signed_in? %>
              <div style="margin-right:-30px;">

                <%= form_tag search_path, method: :get, class: "navbar-form", role: "search" do %>
                  <div class="input-group">
                    <%= text_field_tag(:q, params[:q], { class:"form-control", placeholder: "Search..for frds"}) %>

                      <%= button_tag(:name => nil, type: "submit", class: "btn btn-default") do %>
                         <i class="glyphicon glyphicon-search"></i>
                    <% end %>

                  </div>
                <% end %>

              <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </div>
 </header>

app/views/shared/_notifications.html.erb
<% if notice %>
    <%= javascript_tag "$.notify({
                            // options
                            message: '#{notice}'
                          },{
                            // settings
                            type: 'success',
                            placement: {from: 'top', align: 'center'}
                          });" %>
<% end %>

<% if alert %>
    <%= javascript_tag "$.notify({
                            // options
                            message: '#{alert}'
                          },{
                            // settings
                            type: 'danger',
                            placement: {from: 'top', align: 'center'}
                          });" %>

<% end %>

app/views/users/index.html.erb
<section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            <div class="profile">
              <div class="row">

                <div class="pull-left">
                  <h5 class="page-header"><%= @user.name %></h5>
                  <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-default" %>
                </div>

                <div class="clearfix"></div>

              </div>
              <div class="row">
                <div class="col-md-4">
                  <%= image_tag(@user.avatar.url(:small), alt: @user.name, class: "img-thumbnail") %>
                </div>
                <div class="col-md-8">
                  <ul>
                    <li><strong>Name: </strong><%= @user.name %></li>
                    <li><strong>Email: </strong><%= @user.email %></li>
                    <li><strong>About</strong></li>
                    <li><%= @user.about %></li>
                  </ul>
                </div>
              </div><br><br>
              <div class="row">
                <div class="col-md-12">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h5 class="panel-title">Profile Wall</h5>
                    </div>
                    <div class="panel-body">
                      <% @posts.each do |p| %>
                        <div class="panel panel-default post">
                          <div class="panel-body">
                            <div class="text-left">
                                <%= p.content %>
                            </div>

                            <div class="text-left postedat">
                              <%= time_ago_in_words(p.updated_at) %>
                            </div>
                            <p class="text-left post-actions">
                              <%= link_to "Edit", edit_post_path(p.id), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal'} %>
                              <%= link_to "Delete", post_path(p.id), method: :delete, data: {confirm: t('messages.confirm')} %>
                            </p>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <%= render partial: "shared/following" %>
          </div>

          <div class="col-md-4">
            <div class="panel panel-default friends">
              <div class="panel-heading">
                <h5 class="panel-title">Followers</h5>
              </div>

              <div class="panel-body">
                <% unless @followers.blank? %>
                <ul>
                  <% @followers.each do |fow| %>
                    <li>
                      <%= link_to user_path(fow.current), class: "thumbnail" do %>
                        <%= image_tag(fow.current.avatar.url(:small)) %>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
                <div class="clearfix"></div>
                <%= link_to "View All", showfollowers_path, class: "btn btn-primary" %>
                <% end %>
              </div>

            </div>
          </div>

        </div>
      </div>
    </section>

<div id="edit-
" class="modal fade" role="dialog"></div>

app/views/users/search.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="members">
          <h4 class="page-header">Showing members</h4>
            <div class="row member-row">
              <% if @users.blank? %>
                <div class="text-center">
                  Sorry, no matches found for <b><%= cookies[:search_t] %></b>
                </div>
            </div>
            <% else %>
              <% @users.each do |u| %>
                <div class="row member-row">
                  <div class="col-md-3">
                      <%= image_tag(u.avatar.url(:medium), alt: u.name, class: "img-thumbnail") %>
                      <div class="text-center">
                        <%= u.name %>
                      </div>
                  </div>
                  <div class="col-md-3"></div>

                  <div class="col-md-3">
                      <% if u.id != current_user.id %>
                        <p>
                          <% if current_user.following.exists?(:follower_id => u.id) %>
                            <%= link_to unfollow_path(current_user.following.where(:follower_id => u.id).ids), class: "btn btn-danger btn-block" do %>
                              <i class="fa fa-users"></i>
                               <span>Unfollow</span>
                            <% end %>
                          <% else %>
                            <%= link_to follow_path(u.id), class: "btn btn-primary btn-block" do %>
                              <i class="fa fa-users"></i>
                               <span>Follow</span>
                            <% end %>
                          <% end %>
                        </p>
                      <% end %>
                  </div>

                  <div class="col-md-3">
                      <% if u.id == current_user.id %>
                        <p>
                          <%= link_to "My Profile", users_index_path, class: "btn btn-primary btn-block"%>
                        </p>
                      <% else %>
                        <p>
                          <%= link_to user_path(u), class: "btn btn-primary btn-block" do %>
                            <i class="fa fa-edit"></i>
                             <span>View Profile</span>
                          <% end %>
                        </p>
                      <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 profile">
          <h3 class="page-header"><%= @user.name %></h3>
            <div class="row">
              <div class="col-md-4">
                <%= image_tag(@user.avatar.url(:medium), alt: @user.name, class: "img-thumbnail") %><br>
                <% if @user.id != current_user.id %>
                  <p>
                    <% if current_user.following.exists?(:follower_id => @user.id) %>
                      <%= link_to unfollow_path(current_user.following.where(:follower_id => @user.id).ids), class: "btn btn-danger btn-block" do %>
                        <i class="fa fa-users"></i>
                         <span>Unfollow</span>
                      <% end %>
                    <% else %>
                      <%= link_to follow_path(@user.id), class: "btn btn-primary btn-block" do %>
                        <i class="fa fa-users"></i>
                         <span>Follow</span>
                      <% end %>
                    <% end %>
                  </p>
                <% end %>
              </div>
              <div class="col-md-8">
                <ul>
                  <li><strong>Email: </strong><%= @user.email %></li>
                  <li><strong>About</strong></li>
                  <li><%= @user.about %></li>
                </ul>
              </div>
            </div>
      </div>
    </div>
  </div>
</section>

app/views/users/showfollowers.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="members">
          <h5 class="page-header">Who is following me?</h5>
            <div class="row member-row">
              <% if @followers.blank? %>
                <div class="text-center">
                  Sorry, you don't follow anyone.
                </div>
            </div>
            <% else %>
              <% @followers.each do |u| %>
                <div class="row member-row">
                  <div class="col-md-3">
                      <%= image_tag(u.current.avatar.url(:medium), alt: u.current.name, class: "img-thumbnail") %>
                      <div class="text-center">
                        <%= u.current.name %>
                      </div>
                  </div>
                  <div class="col-md-3"></div>

                  <div class="col-md-3">
                  </div>

                  <div class="col-md-3">
                      <p>
                        <%= link_to user_path(u.current), class: "btn btn-primary btn-block" do %>
                          <i class="fa fa-edit"></i>
                           <span>View Profile</span>
                        <% end %>
                      </p>
                  </div>
                </div>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/showfollowing.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="members">
          <h5 class="page-header">My following list</h5>
            <div class="row member-row">
              <% if @following.blank? %>
                <div class="text-center">
                  Sorry, no one is following you.
                </div>
            </div>
            <% else %>
              <% @following.each do |u| %>
                <div class="row member-row">
                  <div class="col-md-3">
                      <%= image_tag(u.follower.avatar.url(:medium), alt: u.follower.name, class: "img-thumbnail") %>
                      <div class="text-center">
                        <%= u.follower.name %>
                      </div>
                  </div>
                  <div class="col-md-3"></div>

                  <div class="col-md-3">
                      <p>
                        <%= link_to unfollow_path(current_user.following.where(:follower_id => u.follower.id).ids), class: "btn btn-danger btn-block" do %>
                          <i class="fa fa-users"></i>
                           <span>Unfollow</span>
                        <% end %>
                      </p>
                  </div>

                  <div class="col-md-3">
                      <p>
                        <%= link_to user_path(u.follower), class: "btn btn-primary btn-block" do %>
                          <i class="fa fa-edit"></i>
                           <span>View Profile</span>
                        <% end %>
                      </p>
                  </div>
                </div>
              <% end %>

            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>